# Generated by Django 6.0.2 on 2026-03-31 02:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0004_subscription_delete_userfeed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="title",
        ),
    ]
