# Generated by Django 6.0.2 on 2026-03-31 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0005_remove_subscription_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("user", "feed"), name="unique_user_feed_subscription"
            ),
        ),
    ]
