# Generated by Django 6.0.2 on 2026-04-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0007_subscription_title_alter_subscription_feed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="feed.category",
            ),
        ),
    ]
