# Generated by Django 6.0.2 on 2026-04-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0009_feeditem_userfeeditem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeditem",
            name="fetched_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
