# Generated by Django 6.0.2 on 2026-04-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0010_alter_feeditem_fetched_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeditem",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Auto-generated from title",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
    ]
