# Generated by Django 6.0.2 on 2026-04-30 02:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0011_feeditem_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeditem",
            name="slug",
            field=models.SlugField(
                default=django.utils.timezone.now,
                help_text="Auto-generated from title",
                max_length=200,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
