# Generated by Django 6.0.2 on 2026-05-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0012_alter_feeditem_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedsource",
            options={"verbose_name_plural": "sources"},
        ),
        migrations.AddField(
            model_name="feedsource",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
