# Generated by Django 6.0.2 on 2026-08-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0014_feeditem_content_status_alter_category_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeditem",
            name="url",
            field=models.URLField(max_length=2048, unique=True),
        ),
    ]
