# Generated by Django 6.0.2 on 2026-08-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0015_alter_feeditem_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeditem",
            name="image_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
