# Generated by Django 6.0.2 on 2026-08-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0016_alter_feeditem_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeditem",
            name="slug",
            field=models.SlugField(
                help_text="Auto-generated from title", max_length=300, unique=True
            ),
        ),
    ]
