# Generated by Django 6.0.2 on 2026-08-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0017_alter_feeditem_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeditem",
            name="description",
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
